name: Trigger PRFT Quartz Deploy

on:
  push:
    branches:
      - main 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PRFT_PAT }}" \
          https://github.com \
          -d '{"event_type": "dispatch-prft" }' 
