name: Trigger PRFT Quartz Deploy

on:
  push:
    branches:
      - main 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PRFT_PAT }}" \
            --request POST \
            --data '{"event_type": "dispatch_prft" }' https://api.github.com/repos/disctrict/Punk-Rock-Family-Tree/dispatches
